language: node_js
node_js:
  - 8.16.0

before_install:
  - rvm install 2.6.3

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

install:
  - gem install bundler:2.0.2
  - bundler --version
  - make install

script:
  - make build
  - make check

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source

cache: bundler # caching bundler gem packages will speed up build
